spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.20.240:3306/athena?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Liu@1989
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis数据源
  redis:
    host: 39.105.20.240
    port: 6379
    timeout: 6000
    password: Liu@1989
    #    cluster:
    #      nodes: 39.105.20.240:6379,39.105.20.240:6380,39.105.20.240:6381
    #      max-redirects: 3
    lettuce:
      pool:
        max-active: 32  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mail:
    host: smtp.163.com
    username: linxi072@163.com
    password: CMIGMQMFSDGIKTSF
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true